apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: promote-dev-to-main
spec:
  pipelineRef:
    name: ansible-lint-pipeline
  params:
    - name: git-url
      value: https://github.com/rrbanda/ansible-openshift-pipelines.git
    - name: git-revision
      value: dev
    - name: target-repo-url
      value: github.com/rrbanda/ansible-openshift-pipelines.git
    - name: pr-base-branch
      value: main
    - name: target-branch
      value: main
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: ansible-tekton-pvc
