apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: promote-stage-to-prod
spec:
  pipelineRef:
    name: ansible-lint-pipeline
  params:
    - name: git-url
      value: https://github.com/rrbanda/ansible-openshift-pipelines.git
    - name: git-revision
      value: stage
    - name: target-repo-url
      value: github.com/rrbanda/ansible-openshift-pipelines.git
    - name: pr-base-branch
      value: prod
    - name: target-branch
      value: prod
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: ansible-tekton-pvc
