apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ansible-pipeline-run
spec:
  pipelineRef:
    name: ansible-pipeline
  params:
    - name: git-url
      value: https://github.com/rrbanda/ansible-openshift-pipelines.git
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
