apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: spotter-scan
spec:
  workspaces:
    - name: source
  steps:
    - name: step-placeholder-scan
      image: registry.access.redhat.com/ubi9/python-311
      script: |
        #!/bin/bash
        set -euo pipefail
        cd $(workspaces.source.path)

        echo "📦 Cleaning existing clone directory (if any)..."
        rm -rf repo
        mkdir repo && cd repo

        echo "🔐 Spotter scan is currently disabled — no token provided"
        echo "✅ Skipping Spotter scan step safely"
        exit 0
