apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ansible-lint-pipeline
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: dev
    - name: target-repo-url
      type: string
    - name: pr-base-branch
      type: string
    - name: target-branch
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-source
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          subPath: source
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: lint-ansible
      runAfter:
        - clone-source
      taskSpec:
        workspaces:
          - name: shared-workspace
        steps:
          - name: lint
            image: python:3.11
            workingDir: $(workspaces.shared-workspace.path)/source
            script: |
              #!/bin/bash
              set -euo pipefail
              pip install --no-cache-dir ansible-lint
              echo "🔍 Running ansible-lint..."

              mkdir -p ../passed ../failed

              if [ ! -d "samples" ]; then
                echo "❌ No samples folder found. Exiting..."
                exit 1
              fi

              shopt -s nullglob
              for file in samples/*.yml; do
                echo "📂 Checking $file"
                if ansible-lint "$file"; then
                  cp "$file" ../passed/
                else
                  cp "$file" ../failed/
                fi
              done
              shopt -u nullglob

              echo "✅ $(ls ../passed | wc -l) passed"
              echo "❌ $(ls ../failed | wc -l) failed"

              if [ ! "$(ls -A ../passed)" ]; then
                echo "❌ All files failed lint. Failing pipeline."
                exit 1
              fi

    - name: promote-playbook
      runAfter:
        - lint-ansible
      taskRef:
        name: promote-playbook
      workspaces:
        - name: shared
          workspace: shared-workspace
      params:
        - name: target-repo-url
          value: $(params.target-repo-url)
        - name: pr-base-branch
          value: $(params.pr-base-branch)
        - name: target-branch
          value: $(params.target-branch)
