apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ansible-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: git-user-name
      type: string
      default: "ansible-bot"
    - name: git-user-email
      type: string
      default: "bot@example.com"
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: depth
          value: "1"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: bash-validate
      runAfter:
        - clone-repo
      taskRef:
        name: bash-validate
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: python-validate
      runAfter:
        - bash-validate
      taskRef:
        name: python-validate
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: ansible-lint
      runAfter:
        - python-validate
      taskRef:
        name: ansible-lint
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: git-user-name
          value: $(params.git-user-name)
        - name: git-user-email
          value: $(params.git-user-email)
